baseURL = "https://mitchell.to"
title = "Mitchell St Amant"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

[params]
  footer = "Mitchell St Amant"
  description = "Information Technology Leader"
  avatarURL = "/~images/memoji.webp"
  AvatarAltText = "avatar"
  avatarSize = "size-l"
  customHeadHTML = """
    <a rel="me" href="https://twit.social/@drmitch"></a>
  """
    socialIcons = [
    {name = "linkedin", url = "https://linkedin.com/in/mwstamant"},
    {name = "buymeacoffee", url = "https://www.buymeacoffee.com/mwstamant"},
    {name = "mastodon", url = "https://twit.social/@drmitch"},
    {name = "discord", url = "https://discordapp.com/users/846893880107728966"},
    {name = "github", url = "https://github.com/mwstamant"}
  ]
